CREATE TABLE Tarefas (
    Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Titulo VARCHAR(15) NOT NULL,
    Descricao VARCHAR(30) NOT NULL,
    StatusTarefa INT NOT NULL,
    DataDeCriacao TIMESTAMP NOT NULL
)